# Write your MySQL query statement below
SELECT E.NAME AS EMPLOYEE,
E.SALARY AS SALARY,
D.NAME AS DEPARTMENT
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE E.SALARY =(
    SELECT MAX(SALARY) FROM EMPLOYEE WHERE DEPARTMENTID = E.DEPARTMENTID
)